- name: install dependency
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nghttp2-client
- name: add benchmark scripts
  template:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: 0755
  with_items:
    - bench
    - nbench
